command: ["python", "app.py"]

oauth:
  user_api_scopes:
    - sql

env:
  - name: APP_ORG
    value: "sales"
  - name: DATABRICKS_WAREHOUSE_ID
    valueFrom: sql-warehouse
  - name: STATUS_CATALOG
    value: "classic_stable_been2c_catalog"
  - name: STATUS_SCHEMA
    value: "business_reports"
