CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

GRANT INSERT, UPDATE, DELETE ON users TO "";

GRANT USAGE, SELECT, UPDATE ON SEQUENCE users_id_seq TO "";