resources:
  apps:
    ai-parse-doc-visualizer-app:
      name: ai-parse-doc-viz-app
      source_code_path: ../app
      resources: 
        - name: "sql-warehouse"
          description: "A SQL warehouse for app to be able to work with"
          sql_warehouse:
            id: ${var.sql_warehouse_id} 
            permission: "CAN_USE"
        - name: "volume"
          description: "The volume the app will be able to access"
          uc_securable:
            securable_full_name: ${var.uc_volume_path}
            securable_type: "VOLUME"
            permission: "READ_VOLUME"