resources:
  apps:
    alberta-water-well-explorer:
      name: alberta-water-well-explorer
      source_code_path: ../app
      resources: 
        - name: lakebase
          database:
            database_name: ${resources.synced_database_tables.alberta-wdrill-wells-synced-table.logical_database_name}
            instance_name: ${resources.database_instances.alberta-water-well-explorer-instance.name}
            permission: CAN_CONNECT_AND_CREATE