[project]
name = "e2e-python-app-deploy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "databricks-sdk==0.59.0",
    "databricks-sql-connector==4.0.5",
    "pandas==2.2.3",
    "streamlit==1.47.0",
]
